[package]
name = "multicover"
version = "0.1.2"
authors = ["berquerant"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/berquerant/multicover"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
itertools = "0.14.0"